### PR TITLE
feat: friends table

### PR DESCRIPTION
**Pull request by rahuldimri**

### CODE REVIEW

**Comment by rahuldimri** [comment]
/migrate approved

**Migrations failed**: PR author @rahuldimri cannot approve their own PR

**Comment by divyakakroo** [comment]
/migrate approved

Migrations run successfully at 2023-10-03T06:40:22.021Z

**Comment by divyakakroo** [comment]
/migrate approved

Migrations run successfully at 2023-10-03T06:45:50.701Z

**Comment by divyakakroo** [comment]
/migrate approved

Migrations run successfully at 2023-10-03T06:47:54.866Z

**Comment by divyakakroo** [comment]
/migrate approved

Migrations run successfully at 2023-10-03T06:52:03.018Z

**Comment by divyakakroo** [comment]
/migrate approved

Migrations run successfully at 2023-10-03T06:53:08.039Z

**Comment by divyakakroo** [comment]
/migrate dry-run

**[DryRun]Migrations failed** ([execution](https://github.com/varunnayal-org/migrations/actions/runs/1)): Base branch should be **master**

**Comment by varunnayal** [comment]
/migrate approved

**Migrations Successful** at 2023-10-03T10:43:04.087Z

**Comment by varunnayal** [comment]
/migrate dry-run

**[DryRun]Migrations Successful** ([execution](https://api.github.com/repos/varunnayal-org/migrations/actions/runs/6392043708)) at 2023-10-03T10:57:24.816Z

**Comment by varunnayal** [comment]
/migrate dry-run

**[DryRun]Migrations Successful** ([execution](https://github.com/varunnayal-org/migrations/actions/runs/6392063023)) at 2023-10-03T10:59:47.594Z

**Pull request merged**
